# Generated by Django 3.1.3 on 2020-11-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_list_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='orderitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
