# Generated by Django 3.1.3 on 2021-03-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210310_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousorder',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='previousorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
