# Generated by Django 3.1.3 on 2021-03-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210310_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousorder',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
