# Generated by Django 3.1.3 on 2021-03-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_previousorder_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='previousorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='previousorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='PreviousOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('previousorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.previousorder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
