# Generated by Django 3.1.3 on 2021-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210310_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousorderitem',
            name='Ordered_from',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
