# Generated by Django 3.1.3 on 2021-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_previousorderitem_ordered_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousorderitem',
            name='Ordered_from',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
